// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbeXozTPcapH-WErME3yHdnyf8QABQtc',
    appId: '1:179196103843:web:3fe95fc12c1f9c224d8316',
    messagingSenderId: '179196103843',
    projectId: 'ywork-f7082',
    authDomain: 'ywork-f7082.firebaseapp.com',
    storageBucket: 'ywork-f7082.appspot.com',
    measurementId: 'G-F7Z3PWYTPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyvj4XVOt21sfnm614fwomkrTieeapZmY',
    appId: '1:179196103843:android:5421ed13cf5b7d684d8316',
    messagingSenderId: '179196103843',
    projectId: 'ywork-f7082',
    storageBucket: 'ywork-f7082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-wkuo_MNr2fMgxgADFSSkITeStChIIc',
    appId: '1:179196103843:ios:21da451726cc74704d8316',
    messagingSenderId: '179196103843',
    projectId: 'ywork-f7082',
    storageBucket: 'ywork-f7082.appspot.com',
    iosClientId: '179196103843-cv36r1m91jdol0mv3kf6clcmtt2dsul5.apps.googleusercontent.com',
    iosBundleId: 'com.user.mobileApp',
  );
}
